images: ../data/dataset/train/v_-6Os86HzwCs_c009/img1
gt: ../data/dataset/train/v_-6Os86HzwCs_c009/gt/gt_fixed.txt
predictions_dir: ../data/output/SportsMOT/track_with_fix
output_path: ../data/eval_result/SportsMOT/track_with_fix
show-model-names: true
show-ids: true
show-gt: false
save-mp4: true
